export const NewArrivalArray = [
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "1lorem ipsum",
    slug: "1lorem-ipsum",
    price: "7,700 PHP",
    thumbnails: [
      "na-card-a1.jpg",
      "na-card-a2.jpg",
      "na-card-a1.jpg",
      "na-card-a2.jpg",
      "na-card-a1.jpg",
      "na-card-a2.jpg",
      "na-card-a1.jpg",
      "na-card-a2.jpg",
    ],
    sizes: [32, 35, 36, 37, 38],
    rating: 5,
  },
  {
    img1: "na-card-a2.jpg",
    img2: "na-card-a1.jpg",
    title: "2lorem ipsum",
    slug: "2lorem-ipsum",
    price: "7,700 PHP",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [32, 35, 36, 37, 38],
    rating: 2,
  },
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "3lorem ipsum",
    slug: "3lorem-ipsum",
    price: "7,700 PHP",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [32, 35, 36, 37, 38],
  },
  {
    img1: "na-card-a2.jpg",
    img2: "na-card-a1.jpg",
    title: "4lorem ipsum",
    slug: "4lorem-ipsum",
    price: "7,700 PHP",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [32, 35, 36, 37, 38],
    rating: 4,
  },
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "5lorem ipsum",
    slug: "5lorem-ipsum",
    price: "7,700 PHP",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [32, 35, 36, 37, 38],
    rating: 2,
  },
  {
    img1: "na-card-a2.jpg",
    img2: "na-card-a1.jpg",
    title: "6lorem ipsum",
    slug: "6lorem-ipsum",
    price: "7,700 PHP",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [32, 35, 36, 37, 38],
    rating: 1,
  },
];
